### ISSUE TITLE
Initial feedback

### ISSUE THREAD

**Issue by jotomo** [ashkitten/g933-utils#2]
Hi there, excited about the prospect off better linux support for the G933! :-)
Here's what I'm seeing so far, hopefully it's helpful, let me know if I can run any tests to help:

```
mal:~/code/g933-utils/target/debug$ lsusb|grep G933
Bus 003 Device 028: ID 046d:0a5b Logitech, Inc. G933 Wireless Headset Dongle
mal:~/code/g933-utils/target/debug$ git show
commit 922041028a7e80b8133c457510583681c54a4744 (HEAD -> master, origin/master, origin/HEAD)
Author: Ash Levy <ashlea@protonmail.com>
Date:   Sat Jan 27 21:38:12 2018 -0500

    clamp charge between 0 and 100

diff --git a/libg933/src/battery.rs b/libg933/src/battery.rs
index eceab1b..1db89cb 100644
--- a/libg933/src/battery.rs
+++ b/libg933/src/battery.rs
@@ -118,7 +118,7 @@ impl FromBytes for BatteryStatus {
 
         debug!("Voltage graph slope: {}", slope);
 
-        let charge = ((closest_charges.1 - closest_charges.0) * slope) + closest_charges.0;
+        let charge = (((closest_charges.1 - closest_charges.0) * slope) + closest_charges.0).min(0.0).max(100.0);
 
         debug!("Charge: {}", charge);
 
mal:~/code/g933-utils/target/debug$ sudo RUST_BACKTRACE=1 ./g933-utils list
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `238`,
 right: `0`', libg933/src/lib.rs:139:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:68
             at libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: libg933::Device::get_protocol_version::{{closure}}
             at libg933/src/lib.rs:139
   8: <core::result::Result<T, E>>::map
             at /checkout/src/libcore/result.rs:468
   9: libg933::Device::get_protocol_version
             at libg933/src/lib.rs:138
  10: g933_utils::run
             at src/main.rs:53
  11: g933_utils::main
             at src/main.rs:129
  12: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  13: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  14: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  15: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  16: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  17: main
  18: __libc_start_main
  19: _start
```

**Comment by ashkitten** [comment]
Does that happen every time? That assertion is in place to make sure that the ping response matches what was sent.

**Comment by jotomo** [comment]
Yup, every time. I'm on Arch Linux, btw.

**Comment by ashkitten** [comment]
Interesting. Can you try again with the latest commit? That should provide a better error.

**Comment by jotomo** [comment]
I'm getting a compile error now (using nightly rust). 
```
   Compiling libg933 v0.1.0 (file:///home/joe/code/g933-utils/libg933)
error: no rules expected the token `report_buttons`
   --> libg933/src/lib.rs:175:21
    |
175 |                     report_buttons as u8,
    |                     ^^^^^^^^^^^^^^

error: no rules expected the token `volume`
   --> libg933/src/lib.rs:198:21
    |
198 |                     volume,
    |                     ^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `libg933`.
```
I noticed you pushed a commit `better errors` twice but only one is on the branch ... ?

**Comment by ashkitten** [comment]
Ah, my bad. I forgot a couple commas, fixed in the latest commit.

**Comment by jotomo** [comment]
```
ERROR:g933_utils: Ping response did not match the request: was 0
stack backtrace:
   0:     0x55ecc9b55044 - backtrace::backtrace::libunwind::trace::he22146a3af230f57
                        at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h3fa30f8a682c970a
                        at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/backtrace/mod.rs:42
   1:     0x55ecc9b5312c - backtrace::capture::Backtrace::new_unresolved::hefadfdf70bf10705
                        at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/capture.rs:88
   2:     0x55ecc9b51490 - failure::backtrace::internal::InternalBacktrace::new::hf6d4b2feccd084bc
                        at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.1/src/backtrace/internal.rs:44
   3:     0x55ecc9b4fefe - failure::backtrace::Backtrace::new::hf85087d495073ba8
                        at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.1/src/backtrace/mod.rs:98
   4:     0x55ecc9b1ddac - <failure::error::Error as core::convert::From<F>>::from::h3247eb2be526ab4a
                        at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.1/src/error.rs:34
   5:     0x55ecc9b25912 - failure::error_message::err_msg::hf554139c79ae1669
                        at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.1/src/error_message.rs:12
   6:     0x55ecc9b05522 - libg933::Device::get_protocol_version::h497673ecc2be104e
                        at libg933/src/lib.rs:141
   7:     0x55ecc9af8b84 - g933_utils::run::ha73b36f5ef265d22
                        at src/main.rs:53
   8:     0x55ecc9afaf6c - g933_utils::main::hb66a336d92237f07
                        at src/main.rs:129
   9:     0x55ecc9aef8c1 - std::rt::lang_start::{{closure}}::h6d1254a9ac518c65
                        at /checkout/src/libstd/rt.rs:74
  10:     0x55ecc9e14cd7 - std::rt::lang_start_internal::{{closure}}::hf2828f4a2e1e3d69
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::h74480bbab890696d
                        at libstd/panicking.rs:479
  11:     0x55ecc9e2ee5e - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  12:     0x55ecc9e19c63 - std::panicking::try::h03a7eb6553f83ae3
                        at libstd/panicking.rs:458
                         - std::panic::catch_unwind::ha37cc10d40ce6197
                        at libstd/panic.rs:358
                         - std::rt::lang_start_internal::hbc14ab0dbbe6fe26
                        at libstd/rt.rs:58
  13:     0x55ecc9aef8a1 - std::rt::lang_start::hed78542d08ffae1d
                        at /checkout/src/libstd/rt.rs:74
  14:     0x55ecc9afb81d - main
  15:     0x7f064d3a4f49 - __libc_start_main
  16:     0x55ecc9ae1969 - _start
  17:                0x0 - <unknown>
```

**Comment by ashkitten** [comment]
It theoretically should error if you don't have rw access to the device, but maybe it's not? Follow the udev instructions in the README, and try again. If it still doesn't work, make sure you have access to the device by executing `ls -l` on the hidraw paths shown in your kernel log when you plugged in the device.

**Comment by thermatk** [comment]
Hey @jotomo !
since I'm on Arch(Manjaro) as well, maybe we should join issues really 
you didn't get it to list as well yet?
@ashkitten thank you for your babysitting 👍 
I wanted to try your `hidraw` trick now, but it doesn't even always come up as a hidraw device, only after a couple of restickings. Is there a way you forced it on your setup? Will try the quirks thing from here for now: https://hobo.house/2016/01/26/logitech-g933-wireless-headset-linux/

**Comment by jotomo** [comment]
`list` and `get battery` work now with b3420af52d277ab764b750cf943d6190e80476b7 Thanks!

**Comment by jotomo** [comment]
@thermatk Let's just use a Gitter chat room next time? ;-)

**Comment by ashkitten** [comment]
Created a Gitter community and invited you two.
